apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: terroir-tracking-web
  description: Find where your bottle comes from
spec:
  type: website
  lifecycle: production
  owner: tracking-team
  catalog:
    locations:
      - type: url
        target: https://github.com/BelminMahic/tracking-web/blob/main/example.yaml
        rules:
          - allow: [Template]
      - type: file
        target: example.yaml
